### ISSUE TITLE
Default package.json and service name

### ISSUE THREAD

**Issue by tjanczuk** [auth0/serverless-webtasks#11]
When I run 

```
serverless create --template webtasks-nodejs --path my-service
```

I expected to have the `name` in package.json as well as service name in serverless.yml set to `my-service` rather than `webtasks-nodejs`. Otherwise I pretty much always have to go to these 2 places to update the name.

**Comment by rwtombaugh** [comment]
There is also a `--name` option for setting the service name. This code is the serverless FX itself and not our provider...
