### ISSUE TITLE
serverless deploy --secret key=value does not set the secret

### ISSUE THREAD

**Issue by tjanczuk** [auth0/serverless-webtasks#15]
Setting the secret on deploy with `--secret key=value` does not make it available from `ctx.secrets.key` in code.

**Comment by jcenturion** [comment]
`serverless deploy --secretsFile ./secres.json` is not working either

**Comment by rwtombaugh** [comment]
Yes... I need to remove these options from the help text. This is not how secrets works anymore.

**Comment by rwtombaugh** [comment]
I have removed the options for the --help text. So this should now be fixed. Please reinstall the `@webtask/serverless-webtasks` plugin and see if you can repro.
