### ISSUE TITLE
Validate Function File is exporting single thing

### ISSUE THREAD

**Issue by DavidWells** [auth0/serverless-webtasks#3]
Users are used to having multiple functions within a single handler file. We will need to let them know this won't work in webtask right now and tell them to use separate files.

So inside https://github.com/auth0/serverless-webtasks/blob/updateSecrets/lib/shared/webtasksService.js#L122-L139

We need something like:
```js
try {
  const functionFile = require(functionFilePath); 
  // count exports
  // throw/log warning if more than one export found
  console.log("For webtask functions make sure each webtask is in a separate file")
} catch (error) {
  // throw error file not found or permission etc.
}
```

**Comment by rwtombaugh** [comment]
committed your fix for this @DavidWells
